### PR TITLE
Improvements to performance

### PR DESCRIPTION
**Pull request by PieterVanEde**
I noticed some possible small performance improvements, perhaps you agree to them.

### CODE REVIEW

**Comment by adamyork** [comment]
Have you profiled the standalone process with and without these changes ? I'm curious as to what performance gains you are getting.

**Comment by PieterVanEde** [comment]
No I didn't profile this, I just proposed these because I know them to be quick improvements. Profiling might me interesting, but I didn't have the time for that.

**Comment by adamyork** [comment]
The returning of a primitive over an object in this case, I can guarantee will be inconsequential in any modern computing environment. 

I do agree that the regex is unnecessary here. At the very least the pattern and matcher could be declared at the class level; but I can change this to just use the endsWith method on the string as you have in your PR.

I'm going to close this PR because you keep opening them up to the master branch instead of develop. :) But I'll remove the regex in a subsequent commit. Thanks again !

**Comment by PieterVanEde** [comment]
Ah sorry you are right, I should have branched from develop, my bad. Sorry for that. As for the usage of primitives: I disagree with you, but either way it's not a big point anyway. So I'm totally okay if you keep it as it currently is. Keep up the good work on this project.

**Pull request closed without merging**
